version: "3.9"

networks:
    cloakednet:
        name: cloakednet
 
volumes:
    postgres_data:
 
services:

    postgres:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment: 
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
        healthcheck:
            test: pg_isready -d postgres
            interval: 8s
            timeout: 3s
            retries: 2
            start_period: 6s
        deploy:
            resources:
                limits:
                    memory: 256M
        ports:
            - 5432:5432
        networks:
            - cloakednet

    keycloak:
        image: bitnami/keycloak
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABSE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: password
        ports:
            - 3333:8080
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - cloakednet

    viewer:
        build:
            context: ./docker/ohif
        image: ohif-openresty
        env_file: openid-keycloak-secrets.env
        volumes:
            - ./docker/ohif/ohif.js:/var/www/html/app-config.js:ro
            - ./docker/ohif/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
            - ./volumes/logs/nginx:/var/logs/nginx
        depends_on:
            - keycloak
            - orthanc
        restart: always
        ports:
            - '80:80'
        networks:
            - cloakednet

    orthanc:
        image: jodogne/orthanc-plugins:1.5.6
        hostname: orthanc
        volumes:
            - ./docker/orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
            - ./volumes/orthanc-db/:/var/lib/orthanc/db/
        restart: unless-stopped
        networks:
            - cloakednet

